# executable files for this directory
OBJECTS = overflow.exe vec_init.exe incr.exe \
	  warn_dbltoint.exe sizeof_arr.exe sizeof_pgm.exe \
	  cond.exe cond2.exe int-div.exe prec.exe \
	  shift-prec.exe andtest.exe assignment.exe \
	  arraysizeof.exe oknew.exe \
	  cnt_found.exe find_word.exe

# tells make to use the file "..\MS_makefile_template", which
# defines general rules for making .obj and .exe files
include ..\MS_makefile_template

# one or more files in this directory includes a header
# defined in chapter 1
LOCFLAGS = -I..\1


