DIRS = 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18

all:  
	cd 1 && nmake -nologo 
	cd 2 && nmake -nologo 
	cd 3 && nmake -nologo 
	cd 4 && nmake -nologo 
	cd 5 && nmake -nologo 
	cd 6 && nmake -nologo 
	cd 7 && nmake -nologo 
	cd 8 && nmake -nologo 
	cd 9 && nmake -nologo
	cd 10 && nmake -nologo
	cd 11 && nmake -nologo
	cd 12 && nmake -nologo
	cd 13 && nmake -nologo 
	cd 14 && nmake -nologo 
	cd 15 && nmake -nologo 
	cd 16 && nmake -nologo 
	cd 17 && nmake -nologo 
	cd 18 && nmake -nologo 

clean: 
	cd 1 && nmake -nologo clean 
	cd 2 && nmake -nologo clean 
	cd 3 && nmake -nologo clean 
	cd 4 && nmake -nologo clean 
	cd 5 && nmake -nologo clean 
	cd 6 && nmake -nologo clean 
	cd 7 && nmake -nologo clean 
	cd 8 && nmake -nologo clean 
	cd 9 && nmake -nologo clean
	cd 10 && nmake -nologo clean
	cd 11 && nmake -nologo clean
	cd 12 && nmake -nologo clean
	cd 13 && nmake -nologo clean 
	cd 14 && nmake -nologo clean 
	cd 15 && nmake -nologo clean 
	cd 16 && nmake -nologo clean 
	cd 17 && nmake -nologo clean 
	cd 18 && nmake -nologo clean 

clobber: 
	cd 1 && nmake -nologo clobber 
	cd 2 && nmake -nologo clobber 
	cd 3 && nmake -nologo clobber 
	cd 4 && nmake -nologo clobber 
	cd 5 && nmake -nologo clobber 
	cd 6 && nmake -nologo clobber 
	cd 7 && nmake -nologo clobber 
	cd 8 && nmake -nologo clobber 
	cd 9 && nmake -nologo clobber
	cd 10 && nmake -nologo clobber
	cd 11 && nmake -nologo clobber
	cd 12 && nmake -nologo clobber
	cd 13 && nmake -nologo clobber 
	cd 14 && nmake -nologo clobber 
	cd 15 && nmake -nologo clobber 
	cd 16 && nmake -nologo clobber 
	cd 17 && nmake -nologo clobber 
	cd 18 && nmake -nologo clobber 

