# executable files for this directory
OBJECTS = capacity.exe str_print.exe str_assignOps.exe \
	  ctors.exe find_ops.exe stack.exe substr.exe \
	  find-str.exe array_init.exe
	  
# tells make to use the file "..\MS_makefile_template", which
# defines general rules for making .obj and .exe files
include ..\MS_makefile_template

# one or more files in this directory includes a header
# defined in chapter 9
LOCFILE = -I..\9
