# executable files for this directory
OBJECTS = screen3.exe

# tells make to use the file "..\MS_makefile_template", which
# defines general rules for making .obj and .exe files
include ..\MS_makefile_template

screen3.o: screen3.h
