# executable files for this directory
OBJECTS = main_only.exe forcount.exe for_ex.exe whilecount.exe \
	  avg_price.exe add.exe avg_price.exe \
	  item_io.exe add_item.exe add_item2.exe \
	  count.exe userforcount.exe mysum.exe

# tells make to use the file "..\MS_makefile_template", which
# defines general rules for making .obj and .exe files
include ..\MS_makefile_template

