# executable files for this directory
OBJECTS = arr_init.exe  ptr_traversal.exe \
	  copy_array.exe cstring_hdr.exe \
	  cstring_exercise.exe string_exercise.exe \
	  multidim.exe dbl_ptr.exe 

# tells make to use the file "..\MS_makefile_template", which
# defines general rules for making .obj and .exe files
include ..\MS_makefile_template

